name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    name: formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
  tests:
    runs-on: ubuntu-latest
    name: tests
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test
  examples:
    runs-on: ubuntu-latest
    name: examples
    steps:
      - uses: actions/checkout@v4
      - name: Run example minimal
        run: cargo run --example sync_minimal
      - name: Run example polling
        run: cargo run --example sync_polling
      - name: Run example full
        run: cargo run --example full
  benchmarks:
    runs-on: ubuntu-latest
    name: benchmarks
    steps:
      - uses: actions/checkout@v4
      - name: Run bench
        run: cargo bench
