name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    name: formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  build-no-std:
    runs-on: ubuntu-latest
    name: build-no-std
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --no-default-features
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build

  tests-no-std:
    runs-on: ubuntu-latest
    name: tests-no-std
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --no-default-features
  tests:
    runs-on: ubuntu-latest
    name: tests
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test

  examples-no-std:
    runs-on: ubuntu-latest
    name: examples-no-std
    steps:
      - uses: actions/checkout@v4
      - name: Run example no_std_minimal
        run: cargo run --example no_std_minimal --no-default-features
      - name: Run example no_std_full
        run: cargo run --example no_std_full --no-default-features
  examples:
    runs-on: ubuntu-latest
    name: examples
    steps:
      - uses: actions/checkout@v4
      - name: Run example std_minimal
        run: cargo run --example std_minimal
      - name: Run example std_full
        run: cargo run --example std_full

  benchmarks-no-std:
    runs-on: ubuntu-latest
    name: benchmarks-no-std
    steps:
      - uses: actions/checkout@v4
      - name: Run bench
        run: cargo bench --no-default-features
  benchmarks:
    runs-on: ubuntu-latest
    name: benchmarks
    steps:
      - uses: actions/checkout@v4
      - name: Run bench
        run: cargo bench
